Тема “Вычисления с помощью Numpy”


Задание 1


In [0]:
import numpy as np

In [0]:
a = np.array([[1,6],
          [2,8],
          [3,11],
          [3,10],
          [1,7]])

In [34]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [0]:
mean_a=a.mean(axis=0)

In [36]:
mean_a

array([2. , 8.4])

Задание 2

In [0]:
 a_centered = a-mean_a

In [38]:
a_centered.shape

(5, 2)

In [39]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [0]:
 a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])

In [41]:
a_centered_sp

8.0

In [42]:
a_centered_sp/(a.shape[0]-1)

2.0

Задание 4**

In [0]:
cov_matrix=np.cov(m=a.T)

In [44]:
cov_matrix

array([[1. , 2. ],
       [2. , 4.3]])

In [45]:
cov_matrix[0,1]

2.0

Тема “Работа с данными в Pandas”


Задание 1

In [0]:
import pandas as pd
import numpy as np

In [0]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 
                        'author_name': ['Тургенев', 'Чехов', 'Островский']}, 
                      )

In [48]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [0]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     'price':[450, 300, 350, 500, 450, 370, 290]})

In [50]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

In [0]:
authors_price = pd.merge(authors,book, on = 'author_id', how = 'inner')

In [52]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [53]:
top5 = authors_price.nlargest(5, 'price').reset_index(drop=True)
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

Задание 4


In [0]:
authors_stat = authors_price.groupby('author_name')['price'].agg(['max', 'min', 'mean']).reset_index()

In [0]:
authors_stat['mean']=authors_stat['mean'].apply(lambda x: round(x,2))

In [71]:
authors_stat

author_name  max  min    mean
0  Островский  370  290  330.00
1    Тургенев  450  300  366.67
2       Чехов  500  450  475.00

In [0]:
authors_price['cover'] = ['твердая','мягкая','мягкая','твердая','твердая','мягкая','мягкая']

In [73]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [0]:
book_info = pd.pivot_table(data=authors_price, values='price', index='author_name', columns='cover', aggfunc=sum).fillna(0)

In [75]:
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [0]:
book_info.to_pickle('book_info.pkl')

In [0]:
book_info2=pd.read_pickle('book_info.pkl')

In [79]:
book_info2.equals(book_info)

True

In [83]:
book_info2==book_info

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True